src/Entity/Clients.php
<?php

namespace App\Entity;

use App\Repository\ClientsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: ClientsRepository::class)]
class Clients implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 120)]
    private ?string $email = null;

    #[ORM\Column(length: 120)]
    private ?string $password = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */

    #[ORM\Column(length: 100)]
    private ?string $client_nom = null;

    #[ORM\Column(length: 120)]
    private ?string $client_prenom = null;

    #[ORM\Column(length: 120)]
    private ?string $client_adr_rue = null;

    #[ORM\Column(length: 120)]
    private ?string $client_adr_ville = null;

    #[ORM\Column]
    private ?int $client_adr_cp = null;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Commandes::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getClientNom(): ?string
    {
        return $this->client_nom;
    }

    public function setClientNom(string $client_nom): self
    {
        $this->client_nom = $client_nom;

        return $this;
    }

    public function getClientPrenom(): ?string
    {
        return $this->client_prenom;
    }

    public function setClientPrenom(string $client_prenom): self
    {
        $this->client_prenom = $client_prenom;

        return $this;
    }

    public function getClientAdrRue(): ?string
    {
        return $this->client_adr_rue;
    }

    public function setClientAdrRue(string $client_adr_rue): self
    {
        $this->client_adr_rue = $client_adr_rue;

        return $this;
    }

    public function getClientAdrVille(): ?string
    {
        return $this->client_adr_ville;
    }

    public function setClientAdrVille(string $client_adr_ville): self
    {
        $this->client_adr_ville = $client_adr_ville;

        return $this;
    }

    public function getClientAdrCp(): ?int
    {
        return $this->client_adr_cp;
    }

    public function setClientAdrCp(int $client_adr_cp): self
    {
        $this->client_adr_cp = $client_adr_cp;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, Commandes>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commandes $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setClient($this);
        }

        return $this;
    }

    public function removeCommande(Commandes $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getClient() === $this) {
                $commande->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Manifestations.php
<?php

namespace App\Entity;

use App\Repository\ManifestationsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ManifestationsRepository::class)]
class Manifestations
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $manif_titre = null;

    #[ORM\Column(length: 250)]
    private ?string $manif_description = null;

    #[ORM\Column(length: 250)]
    private ?string $manif_casting = null;

    #[ORM\Column(length: 100)]
    private ?string $manif_genre = null;

    #[ORM\Column]
    private ?int $manif_prix = null;

    #[ORM\Column(length: 80)]
    private ?string $manif_affiche = null;

    #[ORM\Column(length: 20)]
    private ?string $manif_date = null;

    #[ORM\Column(length: 10)]
    private ?string $manif_horaire = null;

    #[ORM\ManyToOne(inversedBy: 'salle')]
    private ?Salles $salles = null;

    #[ORM\OneToMany(mappedBy: 'manifestation', targetEntity: Lignescommandes::class)]
    private Collection $lignescommandes;

    public function __construct()
    {
        $this->lignescommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getManifTitre(): ?string
    {
        return $this->manif_titre;
    }

    public function setManifTitre(string $manif_titre): self
    {
        $this->manif_titre = $manif_titre;

        return $this;
    }

    public function getManifDescription(): ?string
    {
        return $this->manif_description;
    }

    public function setManifDescription(string $manif_description): self
    {
        $this->manif_description = $manif_description;

        return $this;
    }

    public function getManifCasting(): ?string
    {
        return $this->manif_casting;
    }

    public function setManifCasting(string $manif_casting): self
    {
        $this->manif_casting = $manif_casting;

        return $this;
    }

    public function getManifGenre(): ?string
    {
        return $this->manif_genre;
    }

    public function setManifGenre(string $manif_genre): self
    {
        $this->manif_genre = $manif_genre;

        return $this;
    }

    public function getManifPrix(): ?int
    {
        return $this->manif_prix;
    }

    public function setManifPrix(int $manif_prix): self
    {
        $this->manif_prix = $manif_prix;

        return $this;
    }

    public function getManifAffiche(): ?string
    {
        return $this->manif_affiche;
    }

    public function setManifAffiche(string $manif_affiche): self
    {
        $this->manif_affiche = $manif_affiche;

        return $this;
    }

    public function getManifDate(): ?string
    {
        return $this->manif_date;
    }

    public function setManifDate(string $manif_date): self
    {
        $this->manif_date = $manif_date;

        return $this;
    }

    public function getManifHoraire(): ?string
    {
        return $this->manif_horaire;
    }

    public function setManifHoraire(string $manif_horaire): self
    {
        $this->manif_horaire = $manif_horaire;

        return $this;
    }

    public function getSalles(): ?Salles
    {
        return $this->salles;
    }

    public function setSalles(?Salles $salles): self
    {
        $this->salles = $salles;

        return $this;
    }

    /**
     * @return Collection<int, Lignescommandes>
     */
    public function getLignescommandes(): Collection
    {
        return $this->lignescommandes;
    }

    public function addLignescommande(Lignescommandes $lignescommande): self
    {
        if (!$this->lignescommandes->contains($lignescommande)) {
            $this->lignescommandes->add($lignescommande);
            $lignescommande->setManifestation($this);
        }

        return $this;
    }

    public function removeLignescommande(Lignescommandes $lignescommande): self
    {
        if ($this->lignescommandes->removeElement($lignescommande)) {
            // set the owning side to null (unless already changed)
            if ($lignescommande->getManifestation() === $this) {
                $lignescommande->setManifestation(null);
            }
        }

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Clients;
use App\Form\ClientType;
use App\Repository\ClientsRepository;
use App\Repository\CommandesRepository;
use App\Repository\LignescommandesRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfilController extends AbstractController
{
    #[Route('/profil', name: 'app_profil')]
    public function index(ClientsRepository $clientsRepository, CommandesRepository $commandesRepository, LignescommandesRepository $lignescommandesRepository): Response
    {
        //get id of current user
        $id = $this->getUser()->getId();
        $client = $clientsRepository->findUserById($id);

        //get all orders of current user
        $commandes = $commandesRepository->findCommandesByUser($id);

        foreach ($commandes as $commande) {
            $lignescommandes = $lignescommandesRepository->findLignesCommandesByCommande($commande);
            foreach ($lignescommandes as $lignecommande) {
                $manifestation[] = $lignecommande->getManifestation();
            }
        }

        return $this->render('profil/index.html.twig', [
            'manifestations' => $manifestation,
            'client' => $client,
            'controller_name' => 'ProfilController',
        ]);
    }

    #[Route('/profil/edit', name: 'app_client_edit')]
    public function edit(ManagerRegistry $doctrine, ClientsRepository $clientsRepository, Request $request): Response
    {
        //get id of current user
        $id = $this->getUser()->getId();
        $client = $clientsRepository->findUserById($id);

        //create form with current user data
        $form = $this->createForm(ClientType::class, $client);
        $form->remove('client_adr_rue');
        $form->remove('client_adr_ville');
        $form->remove('client_adr_cp');
        $form = $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $client = $form->getData();
            $entityManager = $doctrine->getManager();
            $entityManager->persist($client);
            $entityManager->flush();
            return $this->redirectToRoute('app_profil');
        }

        return $this->render('profil/client_edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    //edit adresse
    #[Route('/profil/edit/adresse', name: 'app_client_edit_adresse')]
    public function editAdresse(ManagerRegistry $doctrine, ClientsRepository $clientsRepository, Request $request): Response
    {
        //get id of current user
        $id = $this->getUser()->getId();
        $client = $clientsRepository->findUserById($id);

        //create form with current user data
        $form = $this->createForm(ClientType::class, $client);
        $form->remove('email');
        $form->remove('client_nom');
        $form->remove('client_prenom');
        $form = $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $client = $form->getData();
            $entityManager = $doctrine->getManager();
            $entityManager->persist($client);
            $entityManager->flush();
            return $this->redirectToRoute('app_profil');
        }

        return $this->render('profil/client_edit_adresse.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    //voir commandes
    #[Route('/profil/commandes', name: 'app_client_commandes')]
    public function commandes(ClientsRepository $clientsRepository): Response
    {
        //get id of current user
        $id = $this->getUser()->getId();
        $client = $clientsRepository->findUserById($id);

        return $this->render('profil/client_commandes.html.twig', [
            'client' => $client,
        ]);
    }


}

templates/profil/client_edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}Profil{% endblock %}
{% block meta %}<meta name="robots" content="noindex,nofollow"/>{% endblock %}
{% block stylesheet %} {{ asset('css/profil.css') }} {% endblock %}

{% block body %}

<div class="wrapper">
    <div class="container edit">
        <h2>Editez vos informations</h2>
        {{ form_start(form) }}
        <div class="prenom-nom">
            <div>
                <label>Prénom&nbsp:&nbsp</label> <br> {{ form_widget(form.client_prenom) }}
            </div>
            <div>
                <label>Nom&nbsp:&nbsp</label> <br> {{ form_widget(form.client_nom) }}
            </div>
        </div>
        <div id="email"><label>Email&nbsp:&nbsp</label><br> {{ form_widget(form.email) }}</div>
        {{ form_widget(form.sauvegarder) }}
        {{ form_end(form) }}
</div>
</div>

{% endblock %}

templates/profil/client_edit_adresse.html.twig
{% extends 'base.html.twig' %}
{% block title %}Profil{% endblock %}
{% block meta %}<meta name="robots" content="noindex,nofollow"/>{% endblock %}
{% block stylesheet %} {{ asset('css/profil.css') }} {% endblock %}

{% block body %}

    <div class="wrapper">
    <div class="container edit">
        <h2>Editez votre adresse</h2>
        {{ form_start(form) }}
        <label>Rue&nbsp:&nbsp</label> <br> {{ form_widget(form.client_adr_rue) }}
        <label>Code postal&nbsp:&nbsp</label> <br> {{ form_widget(form.client_adr_cp) }}
        <label>Ville&nbsp:&nbsp</label><br> {{ form_widget(form.client_adr_ville) }}
        {{ form_widget(form.sauvegarder) }}
        {{ form_end(form) }}
    </div>
    </div>

{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Profil{% endblock %}
{% block meta %}<meta name="robots" content="noindex,nofollow"/>{% endblock %}
{% block stylesheet %} {{ asset('css/profil.css') }} {% endblock %}

{% block body %}

<div class="wrapper">

    <h1>Bonjour {{ client.clientPrenom }} {{ client.clientNom }}</h1>

    <div id="infos">
        <div class="container" id="info">
            <h2>Vos Informations</h2>
            <div class="data">
                <p><span class="bold">Email : </span>{{ client.email }}</p>
                <p><span class="bold">Prénom : </span>{{ client.clientPrenom }}</p>
                <p><span class="bold">Nom : </span>{{ client.clientNom }}</p>
            </div>
            <a href="{{ path('app_client_edit', {'id': client.id}) }}" class="button">Modifier</a>
        </div>

        <div class="container" id="adr">
            <h2>Votre adresse</h2>
            <div class="data">
                <p><span class="bold">Adresse : </span>{{ client.clientAdrRue }}</p>
                <p><span class="bold">Ville : </span>{{ client.ClientAdrVille }}</p>
                <p><span class="bold">Code postal : </span>{{ client.ClientAdrCp}}</p>
            </div>
            <a href="{{ path('app_client_edit_adresse', {'id': client.id}) }}" class="button">Modifier</a>
        </div>

        <div class="container">
            <h2>Vos commandes</h2>
            <div class="data">

                {% for manifestation in manifestations %}
                    <div class="commande">
                        <a href="#">
                            <p href="">
                                {{ manifestation.manifTitre }}<br>
                                {{ manifestation.manifDate }} : {{ manifestation.manifHoraire }}
                            </p>
                            <div class="control">
                                <a href="#"><img src="{{ asset('svg/voir.svg') }}" alt="Voir commande"></a>
                                <a href="#"><img src="{{ asset('svg/file.svg') }}" alt="Voir billet"></a>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
            <a href="#" class="button">Voir plus</a>
        </div>
    </div>
</div>

{% endblock %}